# Exported from Render on 2025-07-24T15:24:47Z
services:
  - type: web
    name: n8n
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    plan: free
    envVars:
      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_HOST
        value: ep-gentle-sun-a1o43hza-pooler.ap-southeast-1.aws.neon.tech

      - key: DB_POSTGRESDB_PORT
        value: "5432"

      - key: DB_POSTGRESDB_DATABASE
        value: neondb

      - key: DB_POSTGRESDB_USER
        value: REPLACE_ME_YOURUSER

      - key: DB_POSTGRESDB_PASSWORD
        value: REPLACE_ME_YOURPASSWORD

      - key: DB_POSTGRESDB_SCHEMA
        value: public

      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: "false"

      - key: NODE_ENV
        value: production

      # Optional: enforce SSL mode for Neon
      - key: DB_POSTGRESDB_SSL_MODE
        value: require

      # Security + user management
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "false"
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: "false"

      # Avoid webhook deregistration on shutdown
      - key: N8N_SKIP_WEBHOOK_DEREGISTRATION_SHUTDOWN
        value: "true"

      # Enforce correct config file permissions
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

    region: oregon
    autoDeployTrigger: commit
version: "1"
